aws_access_key = "AKIA2GVX7OYCJIP26J5M"
aws_secret_key = "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"
aws_region = "eu-west-2"
db_name_dev = "mydb"
db_username_dev = "root"
db_password_dev ="vagrant"
db_name_prod = "mydb"
db_username_prod = "root"
db_password_dev = "vagrant"

