apiVersion: v1
kind: Service
metadata:
  name: elb-prod
  namespace: flaskprod
#  annotations:
#    service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: "true"
#    service.beta.kubernetes.io/aws-load-balancer-access-log-emit-interval: "5"
#    service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-name:  "devops-school-diploma-s3-bucket-for-logs"
#    service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-prefix: "/dev"
#  annotations:
#    service.beta.kubernetes.io/access_logs.s3.enabled: "true"
#    service.beta.kubernetes.io/access_logs.s3.bucket:  "devops-school-diploma-s3-bucket-for-logs-test"
#    service.beta.kubernetes.io/access_logs.s3.prefix: "/dev"
spec:
  type: LoadBalancer
  selector:
    app: flaskappprod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

